language: node_js
node_js:
  - 12

branches:
  only:
    - master

notifications:
  email: false

before_script:
  - npm install

script:
  - npm run pack-osx

before_deploy:
  - mv release/the-happy-app-darwin-x64 ./the-happy-app-mac
  - tar -czf the-happy-app-mac.tar.gz the-happy-app-mac
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git tag "$TRAVIS_BRANCH-$(git log --format=%h -1)"

deploy:
  provider: releases
  token: $GHTOKEN
  file:
    - "the-happy-app-mac.tar.gz"
  release_notes: "$TRAVIS_BRANCH: $TRAVIS_COMMIT_MESSAGE"
  target_commitish: $TRAVIS_COMMIT
  skip_cleanup: true
  on:
    all_branches: true
