name: deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: npm install

      - name: Build
        run: npm run pack-osx

      - name: Pack
        run: |
          mv release/the-happy-app-darwin-x64 ./the-happy-app-mac
          tar -czf the-happy-app-mac.tar.gz the-happy-app-mac
          git config --local user.name "${{ secrets.USER_NAME }}"
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git tag "${{ github.ref_name }}-$(git log --format=%h -1)"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: the-happy-app-mac.tar.gz
